#+TITLE: Paracontent
#+AUTHOR: Aleksandr Petrosyan

* Introduction

We live in a world dominated by paracontent.  Not things about other things.  Not ideas.  Content.

But calling something content is too much, in my humble opinion, an honour.  Everything is content.  This article is content.  It has a wrapping interface, the text that you see, the blogging system that put it out there.  The reason why you are reading this text is because you want to glean the wisdom housed therein.  The wisdom is the content.

There is a pre-occupation with referring to filler as content, and every platform is filled with what they call content themselves.  We used to call people writer, filmmaker, orator, composer, musician, scientist, engineer, educator, puzzlemaker, narrative director, and in some cases even amateur pornographer...  Now these all fall into the abstract notion of a /content creator/.  Doesn't matter what you create, because multimedia libraries have homogenised the experience.  Watching TV and watching a movie happens through the same kind of screen.  Music is all on demand, and you can move to any point in the song that you like at any point in time.  Doesn't matter what the composition is, what its structure must be, if there's a short segment that people like, regardless of buildup, they will scroll to that moment.  Same with movies.  Same with TV.  Same with books, actually, but at the very least, the ability to view the elements of the book out-of-order was a property that was inherent in some kinds of books, /e.g./  encyclopaedias and reference books.

Now this is all /content/.

This alone is not infuriating.  In fact, this is how we perceive the world in some ways already.  The move away from manual transcription towards printed books removed some variety in the craft and made us lose some skills, particularly when reading other people's handwriting.  We can debate the merits of our modern print books, and whether they, being as it were mechanical in nature, are better or worse.  It is a fact that we are in a different world, one foreign to the old.

The problem is that we don't even exactly have parity with "content" of the old media.  We don't have content.  We have paracontent.

So what do I mean by that.

* Critics and reactions

Our interaction with most media is decidedly one-sided these days.  We seldom have time to enjoy what used to be the centerpiece of our existence back in the day.  I, as someone who has dedicated more than half of their time all throughout their life to music, no longer have time or the desire to listen to it.  And sure, one /could/ argue that /that/ is because I don't enjoy what most modern producers refer to /as/ music, but that statement would assume that the top charts are indeed the full extent of music production these days.  What about soundtracks?  What about neoclassical.  What about some students "chickenshit" production?  What about amateur recitals?  Music is a lot more than what Spotify force-feeds you.

The problem is that I found that I don't exactly interact with media as much as I used to think that I would.  Back when I was growing up, there was TV.  And it was very much contingent on the local tastes.  So things like "the Simpsons" were only available in the form in which the semi-state-owned channels could afford to broadcast.  We were poor, so going to the cinema happened twice before I was 20.  Once for Men in Black 2, and once more for Madagascar 3.  The choice to engage in media was not up to me, as you can probably tell.  I did not see the Star Wars sequels in theatres, as some kids my age perhaps did.  I did not get to see X-Men the animated series as much as I'd wanted: I'd seen three, maybe four episodes in full.  To be quite fair, there were things that were so much of a cultural phenomenon that I couldn't have /not/ seen them, but even then, if an episode aired when I had something else --  I did not see it.

Choice was a luxury.  And the possibility of having full access to the totality of the media that was ever produced all at once, without any additional space sacrifices, /e.g./  a DVD or blu-ray rack, was unthinkable.  More so, that there would be re-releases of classic media, which made use of modern technology: case in point a 4k HDR version of the Lord Of The Rings.  Much less unfettered access to the expensive equipment that could play these things on demand.  Much less at weird times of day, such as 1am.  Much less, without requiring much forethought about what I want to watch.  If I wanted to watch the third Episode of Star Wars, I'd need to set aside enough money to rent the DVD, go to the rental place, get the actual DVD, take it back, prepare the "everything else" to watch that thing; you know, reserve the time on the machine with a DVD drive, which in my case was my Dad's PC.  As you can probably tell, watching the third Episode was a lot of work.  It took me up until 2011 to do so.  And when I did, the sunken cost fallacy /perhaps/ or more likely the scarcity of better content, led me to liking it.

And now, I'm being told that I liked a bad thing.

And sure enough, for some time, for me it was important to understand the world, the reason /why/ these seemingly smart people tended not to like what was clearly something I found entertaining.  For obvious reasons, to someone who can simply re-watch the Empire Strikes Back whenever they wanted to, they can easily draw comparisons.  I could not.  To me, the Empire Strikes back is all I could remember of it, which was scarcely detailed, and contained quite a few misconceptions[fn:1].

It is quite problematic to reconcile one's perceptions of media, one's tantalising inability to obtain said media, a cathartic ability to finally enjoy said media, and the perceptions of red letter media.

What started out as a means of understanding the critics, and developing one's own tastes in film, devolved into para-film-watching.  A state in which I found myself hopelessly engulfed during the 2020 lockdowns.  You see, the reaction content, and reviews and explanations had become such a routine part of my existence, that I had stopped noticing that I've spent more time watching review content for movies, than said movies.

For a time, I had thought that this is normal.  And from the perspective of overall statistics, that certainly seems to be the case; a lot of people are spending an enormous amount of time interacting with YouTube, TikTok, and other forms of social media.  Which is fine, but consider what they are interacting /with/ and /why/.  As of writing I had ridiculous review of RoboCop 2, a movie that I like quite a bit.  The reviewer isn't someone I particularly (at all) respect.  I didn't feel that I was gaining any useful insight, as I sometimes do from Collative Learning.  I felt that I needed to get some of that in my system.

But here's the kicker: my wife would happily spend an hour watching reels, and even reels about Woodehouse, but not watch Jeeves and Wooster.  And it is not for lack of comedy.  The pacing principles of yore do not apply in the modern day.  Your audience is simply too impatient to get through the ambient introduction of your themes.  The meditative pace of Tarkovskii's Stalker is much too slow for modern viewers.  The modern listeners are much too impatient to listen through an entire song, much less an entire album.  What is the point of talking about media to someone who has no intention of experiencing it?  What is the point of talking about Leo Tolstoy's language, if most people are not going to experience it themselves.  Sure, it's nice to know the rough outline of the story, but if your only source on that is someone else, all you can do at best, is to agree with them.

This is paracontent.  It is related to content, but it is not itself content.  It pertains to the ideas outlined in media as much as your watching someone's YouTube video makes you a friend to them.  In a public forum, one that happens in real life, there  is a potential for back and forth.  In paracontent, there is no such thing.

* One sided paracontent

Here I will touch upon (briefly) the main reason why I think that paracontent is as prevalent as it is.  It is one-sided.  And not in a way in which it would make you suspicious.  No.  It is /naturally/ one-sided.  You are expected to concede that the paracontent cannot have an interaction component, it cannot expect you to do any thinking.  It can only exist, have a thesis and you can either take it or leave it.  Often, humans, flawed though we are, occasionally do the right thing, and leave it.  But most of the time, we do not.  It is an iterated question that only requires you to give in eventually to be effective.  Once that does happen, you will let the proverbial vampire into your house.  And here be vampires indeed.

There is a clear emphasis on authority on platforms such as YouTube.  Consider how crowded is one's live chat during a livestream.  Can you reasonably expect the /content creator/ to respond to all of the given messages in the chat.  Them picking and choosing, or avoiding the tough questions can simply be chalked up to "they can't possibly answer all questions".  And indeed, they cannot.  For us to have a representation on the far end, we must make some form of noise.  As such we seldom think that it is worth holding back to let someone else ask the important questions.  Now imagine that the comments section of a popular video can be populated with comments that were left several decades ago.  Yes, YouTube is /that/ old.  Can you seriously expect the opaque algorithm to boost the questions that would be examining the underpinnings of the /content/?

To me this seems too much of a convenience to be a coincidence.  It may not have been designed that way, but the fact that "traditional" media are dying out in favour of /this/, is what I think is the most important pitfall of modern society.  Facing the music, is one of the most important feedback mechanisms that a human being can possibly have.  Burying one's head in the sand, and pretending that what you do is profound is the most surefire way to become a crackpot.  If I were creating lectures, writing a book, or otherwise participating in a conference, I'd be opening myself up to expert criticism, but also have an opportunity to "fight back".  Creating a YouTube video would

1. Make me vastly more popular in the regular consciousness of regular humans.
2. Make me plausibly unreceptive of the criticism.  I can feign being overwhelmed with other comments, and simply cite their volume to avoid having to engage with long-form discussions.
3. Make the /content/ of what I talk about, plausibly less detailed, because I need to cater to the common non-expert, as opposed to a peer or a superior.

If you were ever wondering why grafters such as Sabine Hossenfelder[fn:3], or her friend Eric Weinstein[fn:2], tend to stick to the renegade scientist persona, and have largely abandoned their original claim to fame: the scientific content, if any were scientific to begin with, is now a super-minority of what they produce, now you know.

* parasocial relationships

It used to be that famous actors and actresses were nothing particularly special.  The world was far less global back then.  

* Footnotes

[fn:3] That seems to have opinions on things that lie far outside her area of expertise, including things like String theory.

[fn:2] That has claimed to have produced a grand unified theory, but when probed about the technical details reverted to a defensive stance of "I lot my notes" and "you have no idea what's it like to work in isolation" (which was self-imposed I must add).

[fn:1] And no, "No!  I am your father."  ranks pretty low.
