#+TITLE: Quantum consciousness
#+AUTHOR: Aleksandr Petrosyan
#+DATE: 2024-05-22

This is an article that got started with motivation that I would genuinely consider problematic.  As is usual, I was reminded that a certain youtuber with a scientific background posted a video about "Penrose being right", and explaining that superradiance inside the cell was somehow proof that consciousness is quantum in nature.

As is usual, I've had full intent of being malicious towards Dr Hossenfelder.  I don't exactly like her; I've made that public.  I've gone to great effort to be as obnoxious in her comment section...  and while I do genuinely stand by that her videos /may/ do more harm than good, I believe that the best thing I can do is ignore the parts which are misleading and focus on what valuable insight can be gained from them.  The reason why I did that shall be expanded upon in another blog post, one that is perhaps a bit too spicy for Greybeard Entertainment, so most likely my personal blog.

Without getting into the sentimental and inflammatory...  I should beg of you to take a drink and a snack, this is going to be a long and bumpy ride.
* The nature of consciousness

The nature of consciousness is an elusive problem that despite being clearly defined within the reach of regular, common sense, seems to not be possible to neatly package into byte-sized analytical chunks and have science give us a clear answer.  This should not surprise you.  Cognising cognition is a self-referential paradox, the kind that bought down mathematics more than once.  What should surprise you (but doesn't) is that the question of "free will" is lumped together, despite being orthogonal and largely a semantic argument: if you believe in superdeterminism, free will doesn't just "not exist", it's ill-defined[fn:1]!

We all know what we mean when a clone in science fiction would say is this the "*you* - you, or the other - you".  Unfrtounately, that is where the clarity of the problem ends.  Some take it into the mystical domain, arguing that consciousness is your soul.  Some take it into the opposite, and equally stupid direction: you have no consciousness, it's all an elaborate illusion.  What I find most painful, is that while the former camp is clearly labelled as a bunch of crackpots that should not be taken seriously, the second camp[fn:2], is considered the /rational point of view/.  The truth of the matter is that we don't know.  Anyone who claims otherwise, have chosen to ignore more than half of the problem, and have thus come up with a meaningless answer.

With that said, there is a surprising resurgence in interest related to the question of what does it mean to understand somehing.  What does it mean to know something.  Is this connected to consciousness, or something that our bodies can do autonomously.  Chomsky's room is a good example of this resurgence, despite the mental experiment being proposed a good few years back, transformer-based next-token prediction machines that show a clear propensity to mimic intelligent discourse have sparked a resurgence in that discussion.  Can machines think?  If machines can think now, can a future machine be built that can?  Does the fact that we are built out of meat and machines are built out of something else matter for the ability to understand and synthesise cognition?  Is symbolic reasoning even necessary to call something conscious?

These are all questions that are sadly overshadowed by the meaningless questions of will thinking machines take away our jobs?  Or would the thinking machines become the Frankenstein's monster that we have been conditioned to fear by what Asimov considered boring science fiction?  Make no mistake, these questions are pertinent in the social climate that GPTs have evolved in.  Humans have recovered from a global pandemic that was thought to be impossible, a period of relative peace had been shattered by wars, across the world and in places where war was considered unthinkable to some.

This happened at a time, whence people have become increasingly aware of the disparity of their economic condition compared to the conditions of those some few decades their younger.  It should not be a surprise that the real potential for Artificial General Intelligence is viewed not as a possibility to overcome the limitations of the human condition; nor as a means to liberate humans from "doing what pays their bills" in favour of "doing what they like"; nor indeed as the ultimate unbiased broker of peace, but as the very instrument of enforcing further restriction; a tool for debasing the poor further and pushing more humans into poverty than ever before; and as  the ultimate and unvanquishable weapon of mass conflict.

If even the simplest questions of "what it means to think" is giving way, there can be no hope of rational discussion on what it means to be conscious, aware and as a fundamental question of being, be.  There will be a discussion of Philosophers that attacked this problem.  I quite enjoy expanding on Nietzsche's ideas, and writings, as I feel that of all the philosophers that are popular in the zeitgest, his works were misunderstood to the point of abuse.  I will say that while this is a philosophical question, I myself, am not a philosopher.  One might even make a good case that I am not a true physicist[fn:3], though it is a career that I pursued with great intent and dreamed of for a quarter of a century.  So expect rough edges.  Expect to call me out.  But do expect a dialogue.  I consider my mission a success, if at the end of this article you have more questions than now.

Ready?
* Penrose and "the emperor's new mind"

I quite liked that book when I was reading it.  I had hoped[fn:4] that it would be less technical, but much Like Sir Roger Penrose's other books it is both thorough, enlightening and a good challenge to grasp.

This book, is divisive.  Unlike his "Road to Reality", widely regarded as a solid text on Physics, if a bit scattered, "The Emperor's New Mind" is touted as a classic, reviled as "total BS" (and that doesn't stand for Bank of Scotland), regarded as a book that asks the important questions and a book that provides misguided answers.  Where I stand on this book is largely going to determine your opinion on this article.  If you think I'm going to either praise it, or criticise it, you're right!  I'll do both.

The praise is that the book clearly and meticulously crafts a narrative: cognition is not as simple as you think.  There are fundamental mathematical problems of computability, because a shocking number of students believe that just throwing more computational power is going to magically yield all answers.  The laws by which our physical reality manifests itself is deterministic, but with the asterisk of only predicting the probabilities of certain outcomes, not the outcomes themselves.  There are mind-bending problems in reconciling that theory, with the theory that explains why the GPS needs to correct for the fact that it's further away from Earth's barycentre than you or I.  There are unsolvable problems in mathematics that basically tell you that even if you could build a machine that could do all known mathematics, there is still unknown mathematics that you could tackle. and there will always be.

The fact of the matter is, Penrose landed in hot water because of a different, and I'd argue somewhat misplaced assertion.  During a polite shouting match at the canteen in Cambridge, I challenged the student that called bullshit on Penrose's entire book; the response was the fact that quantum effects affect only a small part of the physiological processes in the cells.  If anything this indicates a misunderstanding of what Quantum effects really encompass, and further a misunderstanding of what Penrose was indeed trying to argue.  On that we shall elaborate shortly.

** The extent of what we call Quantum

The unfortunate problem that one must deal with, in any discussion that involves the quantum theory, is that huge chunks of it are known very well, others are considered tentatively accepted until a better alternative presents itself, and far too many pieces of it can be chalked up to "we simply don't know".

Yet another observation that eludes most participants in discussions of Quantum theory, is that it is not /just/, in fact, as some would have you believe, /a theory of physics/, but also a novel theory of probability that only got interpreted as such, because of new physical phenomena.  People have known about wave optics for a long time before it was understood to be a universal[fn:5] set of laws that equally applies to pure particles.

Complex numbers were finally[fn:6] being accepted into mainstream mathematics, despite being incredibly useful tools for many centuries beforehand, only when the predictions of quantum theory started to become apparent in everyday phenomena.

To elaborate on that part, consider that probability outside of quantum mechanics concerns itself with phenomena whose likely-ness[fn:7] is a single positive finite number.  For convenience, all of these numbers are re-scaled to the interval $[0, 1]$, but could, for all intents and purposes any other larger interval offset in any direction by any amount.  But in the "classical world" as in statistics outside of quantum effects, if the numbers are shifted into the negative, probabilities no longer work.  By modifying the theory, usually by introducing a probability amplitude, and consequently allowing both a constructive and destructive interference between different chains of events, one can construct a different kind of theory of probability.  That theory, coupled with some insights from linear algebra, allow one to construct a mechanics for waves and quanta[fn:8].

Wave mechanics, a.k.a. Quantum mechanics, houses some of the weirdest phenomena, that boggle the untrained mind.  It is a remarkably consistent theory that through something known as the /correspondence principle/ should govern all of reality.  Unfortunately, while this theory works remarkably well at the smaller scales, and through Ehrenfest's theorem explains most phenomena at the Newtonian scale, it cannot, on its own, and without modification, explain what happens at the larger scales.  We do, however, know some parts of the logic that must be preserved in a theory that encompasses every known physical phenomenon, and unfortunately, amplitude statistics is something that must be present in the greater theory in some way shape or form.  In other words, Bell's theorem, must hold.

Bell's theorem is a particularly problematic result for anyone who wishes to neatly package the laws of the universe into a single (update) function.  It runs counter to one's notion of classical determinism; that dynamical values are just that -- numbers.  It does not, and this must be emphasised, *preclude determinism as a whole*; if one thinks of state as vectors in a Hilbert space, and observable quantities as operators, there's a perfectly valid definition of determinism.  True, the observables are still random  and the order in which you take measurements makes a huge difference, but that is just the nature of reality.  The fact of the matter is, that the wave-function is a deterministic beast.

The reason why I believe that Penrose was misunderstood is that people assign him one point of view, and ignore the subtlety in it.  Quantum mechanics is not a loophole that lets you have free will, if you believed you didn't have it, the principle hasn't changed: you are still a physical object that cannot violate the laws of physics, so whether or not something is conscious[fn:9], is irrelevant[fn:10] in Physics.  Within the scope of Physics, there are questions that cannot be answered at all.  Paul A. M.  Dirac, famously stated that it is beyond physics to try and understand why a particular electron goes through a particular hole.  Dirac had a remarkable intuition, and was a firm believer in locality, so it is not beyond the realm of possibility that he assumed something like Bell's theorem was true.  Given that "The principles of Quantum Mechanics" was published in 1930, and Bell's theorem in 1981, the only other reasonable explanation is that Bell was guided by that statement to see if it were actually true, what the consequences would be.

For the sake of argument, and I will be covering both Bell's theorem, locality and principles of Quantum mechanics in other blog posts...  it is a good exercise for me to recall what that subject is all about, especially now.  Bell's theorem, one for which conclusive experimental evidence (closing of so-called loopholes) resulted in a very recent Nobel Prize in physics, states that: "Quantum mechanics is either local, or observable-deterministic".  That is the extent of it.  Einstein, in this situation is the person with most discontent: according to him the theory must be both realistic, /i.e./  having ways of determining the observables, we just don't know what yet, and local, /i.e./ what happens here can only be determined by causally linked events.  Einstein is wholly dissatisfied, because he needs both principles.  Most other scientists are partly satisfied and in the following way.

If you want to believe pilot wave theory, and you ignore for the moment what it would mean to create the equivalent of QFT for it (quite an exercise if you think about it), you can state that "OK, there are particles riding waves, there's some probability that particles will follow the pilot wave's large crest or the smaller crest, and we don't know which one, and we can't tell which one, (just like in the mainstream interpretation), but we know for sure that it is realistic.  The problem, here, though, is that the pilot wave can be affected arbitrarily quickly.  It is an even more mysterious quantity than the wavefunction as a consequence.  Similarly, most modern interpretations insist on the things being preferably local.

* Footnotes

[fn:1] The reader might recall Robert Sapolski writing a book, a case against free will.  I don't if it is worth discussing his book, as unlike the question of consciousness, free will is both properly defined, and the non-existence of such an entity is proven to the best of our scientific knowledge.  There is nothing to discuss there.  Read the book!

[fn:2] and I should be very specific that I don't talk about Dennett here, but rather about some that don't quite understand his teaching,

[fn:3] Which given the climate of LK99, mass retractions and scandals involving falsified and plagiarised work, I tend to view more as a compliment.

[fn:4] Assuming I could gift a hardcover to my wife, who is not a physicist nor particularly attuned to mathematics, but has tremendous respect for both.

[fn:5] Louis DeBroglie being one famous proponent of this idea

[fn:6] Up to this day, there are those who would find the idea of complex numbers preposterous fudgery.  The square root of negative one is to this day called the _imaginary_ unit.

[fn:7] To avoid a precisely defined Bayesian term: likelihood.

[fn:8] If one squints really hard, one could also construct the same mechanics without complex numbers, just by allowing negative probabilities...  that construction has the same properties as the geocentric model; technically it reproduces most of the theoretical results, but is also unnecessarily cumbersome.

[fn:9] We must, of course, talk about the very important interpretation of Quantum mechanics that very nearly discredited it in the eyes of rationalists.  Deepak Chopra very nearly brought Quantum mechanics to the level of mysticism and essential oils.  Whether or not there is truth to his teaching is a curious matter to which we have no answer.  Whether or not his methods were scientific is a closed case with a resounding /no/.

[fn:10] This is my personal belief, and not specifically a property of the current interpretation of Quantum mechanics that is in vogue, nor necessarily of the person that subscribes to the belief that Quantum determinism is determinism.
